-- 화성인사이드 DB/Auth/Storage v1
-- Supabase SQL Editor에서 전체 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_]{4,20}$'),
  role text not null default 'member' check (role in ('admin','editor','member')),
  status text not null default 'active' check (status in ('active','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  name text not null default '',
  job text not null default '',
  age integer,
  gender text default '',
  public_email text default '',
  school text default '',
  area text default '',
  tier text not null default 'Gold',
  tags jsonb not null default '[]'::jsonb,
  intro text default '',
  profile_image_url text default '',
  featured_rank integer unique check (featured_rank between 1 and 10),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.careers (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  sort_order integer not null default 0,
  period text default '',
  company text default '',
  role text default '',
  description text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.site_state (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.news_posts (
  id bigint generated by default as identity primary key,
  category text not null default '공지',
  title text not null default '',
  excerpt text default '',
  body text default '',
  cover_url text default '',
  is_published boolean not null default false,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.my_role()
returns text language sql stable security definer set search_path=public as $$
  select coalesce((select role from public.app_users where user_id=auth.uid()), 'member');
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.app_users(user_id,username,role,status)
  values(new.id,lower(trim(coalesce(new.raw_user_meta_data->>'username',''))),'member','active')
  on conflict(user_id) do nothing;
  update public.members set user_id=new.id, updated_at=now()
    where user_id is null and lower(public_email)=lower(coalesce(new.email,''));
  if not found then
    insert into public.members(user_id,name,job,public_email,is_published)
    values(new.id,coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.raw_user_meta_data->>'job',''),coalesce(new.email,''),true);
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.app_users enable row level security;
alter table public.members enable row level security;
alter table public.careers enable row level security;
alter table public.site_state enable row level security;
alter table public.news_posts enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "app_users_self_read" on public.app_users;
create policy "app_users_self_read" on public.app_users for select using (user_id=auth.uid());

drop policy if exists "members_public_read" on public.members;
create policy "members_public_read" on public.members for select using (is_published or user_id=auth.uid() or public.my_role() in ('admin','editor'));

drop policy if exists "careers_public_read" on public.careers;
create policy "careers_public_read" on public.careers for select using (exists(select 1 from public.members m where m.id=member_id and (m.is_published or m.user_id=auth.uid() or public.my_role() in ('admin','editor'))));

drop policy if exists "site_state_public_read" on public.site_state;
create policy "site_state_public_read" on public.site_state for select using (true);

drop policy if exists "news_public_read" on public.news_posts;
create policy "news_public_read" on public.news_posts for select using (is_published or public.my_role() in ('admin','editor'));

drop policy if exists "audit_admin_read" on public.audit_logs;
create policy "audit_admin_read" on public.audit_logs for select using (public.my_role()='admin');

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('hwaseong-media','hwaseong-media',true,12582912,array['image/jpeg','image/png','image/webp','image/svg+xml'])
on conflict(id) do update set public=true,file_size_limit=12582912,allowed_mime_types=excluded.allowed_mime_types;

-- 공개 버킷 읽기 허용. 쓰기는 앱 서버의 service-role API에서만 수행합니다.
drop policy if exists "hwaseong_media_public_read" on storage.objects;
create policy "hwaseong_media_public_read" on storage.objects for select using (bucket_id='hwaseong-media');

-- v6 operating fields
alter table public.members add column if not exists youtube_url text default '';
alter table public.members add column if not exists youtube_thumbnail_url text default '';
create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  board_type text not null check (board_type in ('notice','community')),
  title text not null default '', body text not null default '', excerpt text default '', cover_url text default '', youtube_url text default '',
  author_id uuid references auth.users(id) on delete set null, author_name text default '', is_published boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.board_posts enable row level security;
drop policy if exists "board_public_read" on public.board_posts;
create policy "board_public_read" on public.board_posts for select using (is_published = true or author_id = auth.uid() or public.my_role() in ('admin','editor'));
