'use client';
import { useEffect,useState } from 'react';
import { PageTitle,Card,Field,Input,Textarea,Badge } from '../../../components/admin/AdminUI';
export default function BoardsAdmin(){
 const [type,setType]=useState('notice'),[posts,setPosts]=useState([]),[selected,setSelected]=useState(''),[msg,setMsg]=useState('');
 async function load(t=type){const r=await fetch(`/api/boards/${t}`,{cache:'no-store'});const d=await r.json();if(r.ok){setPosts(d.posts||[]);setSelected(s=>(d.posts||[]).some(x=>String(x.id)===String(s))?s:String(d.posts?.[0]?.id||''));}else setMsg(d.error||'불러오기 실패')}
 useEffect(()=>{load(type)},[type]); const p=posts.find(x=>String(x.id)===String(selected));
 const set=(k,v)=>setPosts(a=>a.map(x=>x.id===p.id?{...x,[k]:v}:x));
 async function save(){if(!p)return;setMsg('저장 중...');const r=await fetch(`/api/boards/${type}/${p.id}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const d=await r.json();setMsg(r.ok?'저장되었습니다.':d.error||'저장 실패');if(r.ok)load(type)}
 async function del(){if(!p||!confirm('게시물을 삭제할까요?'))return;const r=await fetch(`/api/boards/${type}/${p.id}`,{method:'DELETE'});setMsg(r.ok?'삭제되었습니다.':'삭제 실패');if(r.ok)load(type)}
 return <div className="adminPage"><PageTitle title="게시판 관리" desc="공지게시판과 커뮤니티게시판의 회원 글을 확인하고 관리자는 수정·삭제할 수 있습니다." actions={<div className="adminBoardTabs"><button className={type==='notice'?'active':''} onClick={()=>setType('notice')}>공지게시판</button><button className={type==='community'?'active':''} onClick={()=>setType('community')}>커뮤니티</button></div>}/><div className="adminMemberLayout"><Card title="게시물 목록"><div className="adminNewsList">{posts.map(x=><button key={x.id} className={String(x.id)===String(selected)?'active':''} onClick={()=>setSelected(String(x.id))}><span><b>{x.title}</b><small>{x.author_name} · {(x.created_at||'').slice(0,10)}</small></span><Badge type={x.youtube_url?'purple':'green'}>{x.youtube_url?'영상':'글'}</Badge></button>)}</div></Card>{p&&<Card title="게시물 수정" desc={msg||'회원이 작성한 글도 관리자가 수정·삭제할 수 있습니다.'}><div className="adminFormGrid"><Field label="제목"><Input value={p.title||''} onChange={e=>set('title',e.target.value)}/></Field><Field label="작성자"><Input value={p.author_name||''} disabled/></Field><Field label="유튜브 URL"><Input value={p.youtube_url||''} onChange={e=>set('youtube_url',e.target.value)} placeholder="https://youtu.be/..."/></Field><Field label="대표 이미지 URL"><Input value={p.cover_url||''} onChange={e=>set('cover_url',e.target.value)}/></Field><Field label="본문"><Textarea rows={15} value={p.body||''} onChange={e=>set('body',e.target.value)}/></Field></div><div className="adminActionRow"><button className="adminBtn primary" onClick={save}>수정 저장</button><button className="adminBtn danger" onClick={del}>삭제</button></div></Card>}</div></div>
}
