'use client';
import { useEffect,useMemo,useState } from 'react';
import { useAdmin } from '../../../components/admin/AdminStore';
import { PageTitle, Card, Field, Input, Textarea, ImageUploader, Badge } from '../../../components/admin/AdminUI';
import { IMAGE_SPECS,DEFAULT_STRENGTHS } from '../../../data/adminDefaults';
const strengthLabels=['창의','연결','통찰','공감','실행','성장'];
const parseTags=v=>[...new Set(String(v||'').split(/[\n,\/]+|\s+(?=#)/g).map(x=>x.trim().replace(/^#+/,'')).filter(Boolean))];
const tagGuide='입력 예시: 마케팅,기획,디자인 · 영화/문화/기획 · #마케팅 #종교자';
export default function MembersAdmin(){
 const {members,updateMember}=useAdmin(); const [q,setQ]=useState(''); const [selected,setSelected]=useState('1'); const [tagText,setTagText]=useState('');
 const filtered=useMemo(()=>members.filter(m=>(String(m.name||'')+String(m.job||'')).toLowerCase().includes(q.toLowerCase())),[members,q]); const m=members.find(x=>String(x.id)===String(selected))||members[0];
 useEffect(()=>{setTagText((m?.tags||[]).join(', '))},[m?.id]);
 function patchCareer(i,patch){const careers=[...(m.careers||[])];careers[i]={...careers[i],...patch};updateMember(m.id,{careers})}
 function moveCareer(i,delta){const careers=[...(m.careers||[])];const ni=i+delta;if(ni<0||ni>=careers.length)return;[careers[i],careers[ni]]=[careers[ni],careers[i]];updateMember(m.id,{careers})}
 function removeCareer(i){updateMember(m.id,{careers:(m.careers||[]).filter((_,j)=>j!==i)})}
 if(!m)return <div className="adminPage"><PageTitle title="회원 관리" desc="등록된 회원이 없습니다."/></div>;
 return <div className="adminPage"><PageTitle title="회원 관리" desc="회원 본인이 입력한 상세 프로필을 관리자가 같은 항목 기준으로 수정할 수 있습니다."/>
  <div className="adminMemberLayout"><Card title="회원 목록" className="adminMemberListCard"><Input placeholder="이름 또는 직책 검색" value={q} onChange={e=>setQ(e.target.value)}/><div className="adminMemberList">{filtered.map(x=><button key={x.id} className={String(x.id)===String(m.id)?'active':''} onClick={()=>setSelected(x.id)}><img src={x.profileImage||x.image||''} alt=""/><span><b>{x.name}</b><small>{x.job}</small></span>{x.featured&&<Badge type="purple">Top10</Badge>}</button>)}</div></Card>
  <Card title={`${m.name} 상세 프로필 수정`} desc="저장된 정보는 회원 상세페이지에 즉시 반영됩니다."><div className="adminMemberEditor">
   <ImageUploader label="프로필 원본 이미지" value={m.profileImage||m.image} onChange={v=>updateMember(m.id,{profileImage:v,image:v})} spec={IMAGE_SPECS.memberProfile}/>
   <div className="adminFormGrid"><Field label="이름"><Input value={m.name||''} onChange={e=>updateMember(m.id,{name:e.target.value})}/></Field><Field label="직업 / 직책"><Input value={m.job||''} onChange={e=>updateMember(m.id,{job:e.target.value})}/></Field><Field label="한 줄 소개 / 슬로건"><Input value={m.tagline||''} onChange={e=>updateMember(m.id,{tagline:e.target.value})}/></Field><Field label="등급"><select className="adminInput" value={m.tier||'Gold'} onChange={e=>updateMember(m.id,{tier:e.target.value})}><option>Gold</option><option>Platinum</option></select></Field><Field label="나이"><Input type="number" value={m.age||''} onChange={e=>updateMember(m.id,{age:Number(e.target.value)})}/></Field><Field label="성별"><Input value={m.gender||''} onChange={e=>updateMember(m.id,{gender:e.target.value})}/></Field><Field label="이메일"><Input value={m.email||''} onChange={e=>updateMember(m.id,{email:e.target.value})}/></Field><Field label="전화번호"><Input type="tel" value={m.phone||''} onChange={e=>updateMember(m.id,{phone:e.target.value})} placeholder="010-0000-0000"/></Field><Field label="최종학력"><Input value={m.school||''} onChange={e=>updateMember(m.id,{school:e.target.value})}/></Field><Field label="활동지역"><Input value={m.area||''} onChange={e=>updateMember(m.id,{area:e.target.value})}/></Field><Field label="프로필 공개"><select className="adminInput" value={m.published===false?'private':'public'} onChange={e=>updateMember(m.id,{published:e.target.value==='public'})}><option value="public">공개</option><option value="private">비공개</option></select></Field><Field label="전문분야 / 해시태그" hint={tagGuide}><Input value={tagText} onChange={e=>setTagText(e.target.value)} onBlur={()=>{const tags=parseTags(tagText);updateMember(m.id,{tags});setTagText(tags.join(', '))}} placeholder="마케팅,기획,디자인"/></Field><Field label="개인정보 소개"><Textarea rows={8} value={m.intro||''} onChange={e=>updateMember(m.id,{intro:e.target.value})}/></Field><Field label="상세페이지 유튜브 URL"><Input value={m.youtubeUrl||''} onChange={e=>updateMember(m.id,{youtubeUrl:e.target.value})} placeholder="https://youtu.be/..."/></Field></div>
   <ImageUploader label="회원 상세 영상 썸네일" value={m.youtubeThumbnailUrl||''} onChange={v=>updateMember(m.id,{youtubeThumbnailUrl:v})} spec={IMAGE_SPECS.memberVideoThumbnail}/>
   <div className="adminStrengthEdit"><h3>회원 셀프 어필 강점 (0~100)</h3><div>{strengthLabels.map(k=><Field key={k} label={k}><Input type="number" min="0" max="100" value={k==='통찰'?((m.strengths||{}).통찰??(m.strengths||{}).분석??80):((m.strengths||DEFAULT_STRENGTHS)[k]??80)} onChange={e=>updateMember(m.id,{strengths:{...DEFAULT_STRENGTHS,...(m.strengths||{}),[k]:Math.max(0,Math.min(100,Number(e.target.value)||0))}})}/></Field>)}</div></div>
   <div className="adminCareerEdit"><div className="careerEditorHead"><div><h3>경력 · 이력</h3><p>경력을 추가·삭제하고, 위/아래 버튼으로 상세페이지 노출 순서를 바꿀 수 있습니다.</p></div><button type="button" className="adminBtn primary" onClick={()=>updateMember(m.id,{careers:[...(m.careers||[]),{period:'',company:'',role:'',desc:''}]})}>+ 경력 추가</button></div>{(m.careers||[]).map((c,i)=><div className="adminCareerRow" key={`${m.id}-${i}`}><div className="careerOrderBadge">{i+1}</div><div className="careerFields"><Input placeholder="기간" value={c.period||''} onChange={e=>patchCareer(i,{period:e.target.value})}/><Input placeholder="회사/기관" value={c.company||''} onChange={e=>patchCareer(i,{company:e.target.value})}/><Input placeholder="직책·역할" value={c.role||''} onChange={e=>patchCareer(i,{role:e.target.value})}/><Input placeholder="주요 역할 설명" value={c.desc||''} onChange={e=>patchCareer(i,{desc:e.target.value})}/></div><div className="careerRowActions"><button type="button" onClick={()=>moveCareer(i,-1)} disabled={i===0}>↑ 위로</button><button type="button" onClick={()=>moveCareer(i,1)} disabled={i===(m.careers||[]).length-1}>↓ 아래로</button><button type="button" className="danger" onClick={()=>removeCareer(i)}>삭제</button></div></div>)}</div>
  </div></Card></div></div>
}
