'use client';
import { useMemo,useState } from 'react';
import { useAdmin } from '../../../components/admin/AdminStore';
import { PageTitle, Card, Field, Input, Textarea, ImageUploader, Badge } from '../../../components/admin/AdminUI';
import { IMAGE_SPECS } from '../../../data/adminDefaults';
export default function MembersAdmin(){
 const {members,updateMember}=useAdmin(); const [q,setQ]=useState(''); const [selected,setSelected]=useState('1');
 const filtered=useMemo(()=>members.filter(m=>(m.name+m.job).toLowerCase().includes(q.toLowerCase())),[members,q]); const m=members.find(x=>String(x.id)===String(selected))||members[0];
 return <div className="adminPage"><PageTitle title="회원 관리" desc="회원가입 프로필을 기반으로 메인·Top10·상세페이지에 동일 데이터를 자동 연동하는 구조입니다."/>
  <div className="adminMemberLayout"><Card title="회원 목록" className="adminMemberListCard"><Input placeholder="이름 또는 직책 검색" value={q} onChange={e=>setQ(e.target.value)}/><div className="adminMemberList">{filtered.map(x=><button key={x.id} className={String(x.id)===String(m.id)?'active':''} onClick={()=>setSelected(x.id)}><img src={x.profileImage||x.image} alt=""/><span><b>{x.name}</b><small>{x.job}</small></span>{x.featured&&<Badge type="purple">Top10</Badge>}</button>)}</div></Card>
  <Card title={`${m.name} 프로필 수정`} desc="관리자는 전체 수정, 일반 회원은 자신의 프로필만 수정하도록 권한을 분리할 예정입니다."><div className="adminMemberEditor">
   <ImageUploader label="프로필 원본 이미지" value={m.profileImage||m.image} onChange={v=>updateMember(m.id,{profileImage:v,image:v})} spec={IMAGE_SPECS.memberProfile}/>
   <div className="adminFormGrid"><Field label="이름"><Input value={m.name} onChange={e=>updateMember(m.id,{name:e.target.value})}/></Field><Field label="직업 / 직책"><Input value={m.job} onChange={e=>updateMember(m.id,{job:e.target.value})}/></Field><Field label="나이"><Input type="number" value={m.age} onChange={e=>updateMember(m.id,{age:Number(e.target.value)})}/></Field><Field label="성별"><Input value={m.gender} onChange={e=>updateMember(m.id,{gender:e.target.value})}/></Field><Field label="이메일"><Input value={m.email} onChange={e=>updateMember(m.id,{email:e.target.value})}/></Field><Field label="최종학력"><Input value={m.school} onChange={e=>updateMember(m.id,{school:e.target.value})}/></Field><Field label="활동지역"><Input value={m.area} onChange={e=>updateMember(m.id,{area:e.target.value})}/></Field><Field label="해시태그" hint="쉼표로 구분"><Input value={(m.tags||[]).join(', ')} onChange={e=>updateMember(m.id,{tags:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/></Field><Field label="개성있는 소개"><Textarea rows={7} value={m.intro} onChange={e=>updateMember(m.id,{intro:e.target.value})}/></Field></div>
   <div className="adminCareerEdit"><h3>경력 · 이력</h3>{(m.careers||[]).map((c,i)=><div key={i}><Input value={c.period} onChange={e=>{const careers=[...m.careers];careers[i]={...careers[i],period:e.target.value};updateMember(m.id,{careers})}}/><Input value={c.company} onChange={e=>{const careers=[...m.careers];careers[i]={...careers[i],company:e.target.value};updateMember(m.id,{careers})}}/><Input value={c.role} onChange={e=>{const careers=[...m.careers];careers[i]={...careers[i],role:e.target.value};updateMember(m.id,{careers})}}/><Input value={c.desc} onChange={e=>{const careers=[...m.careers];careers[i]={...careers[i],desc:e.target.value};updateMember(m.id,{careers})}}/></div>)}</div>
  </div></Card></div></div>
}
