'use client';
import { useEffect,useState } from 'react';
import { createClient } from '../../lib/supabase/client';

const strengthLabels=['창의','연결','통찰','공감','실행','성장'];
const defaultStrengths={창의:80,연결:80,통찰:80,공감:80,실행:80,성장:80};
const parseTags=v=>[...new Set(String(v||'').split(/[\n,\/]+|\s+(?=#)/g).map(x=>x.trim().replace(/^#+/,'')).filter(Boolean))];
const tagGuide='입력 예시: 마케팅,기획,디자인 · 영화/문화/기획 · #마케팅 #종교자';

export default function AccountClient({user}){
 const [m,setM]=useState(null);const [msg,setMsg]=useState('');const [uploading,setUploading]=useState(false);const [thumbUploading,setThumbUploading]=useState(false);const [tagText,setTagText]=useState('');
 useEffect(()=>{fetch('/api/profile').then(r=>r.json()).then(d=>{const member=d.member||{};member.careers=(member.careers||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(c=>({...c,_key:c.id||`career-${crypto.randomUUID?.()||Math.random()}`}));const old=member.strengths||{};member.strengths={...defaultStrengths,...old,통찰:old.통찰??old.분석??80};delete member.strengths.분석;setTagText((member.tags||[]).join(', '));setM(member)});},[]);
 const set=(k,v)=>setM(p=>({...p,[k]:v}));
 async function save(){const tags=parseTags(tagText);setMsg('저장 중...');const payload={...m,tags,careers:(m.careers||[]).map(({_key,...c})=>c)};const r=await fetch('/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(r.ok){setM(p=>({...p,tags}));setTagText(tags.join(', '));setMsg('저장되었습니다. 상세페이지에 바로 반영됩니다.')}else setMsg(d.error||'저장 실패');}
 async function uploadAsset(e,field,folder,setBusy){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMsg('');const fd=new FormData();fd.append('file',file);fd.append('folder',folder);const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(r.ok){set(field,d.url);setMsg('이미지가 업로드되었습니다. 프로필 저장을 눌러 반영해 주세요.')}else setMsg(d.error||'업로드 실패');setBusy(false);e.target.value=''}
 function updateCareer(i,patch){setM(p=>{const careers=[...(p.careers||[])];careers[i]={...careers[i],...patch};return {...p,careers}})}
 function removeCareer(i){setM(p=>({...p,careers:(p.careers||[]).filter((_,j)=>j!==i)}))}
 function moveCareer(i,delta){setM(p=>{const careers=[...(p.careers||[])];const ni=i+delta;if(ni<0||ni>=careers.length)return p;[careers[i],careers[ni]]=[careers[ni],careers[i]];return {...p,careers}})}
 function addCareer(){setM(p=>({...p,careers:[...(p.careers||[]),{_key:`new-${Date.now()}-${Math.random()}`,period:'',company:'',role:'',description:''}]}))}
 async function logout(){const supabase=createClient();await supabase.auth.signOut();location.href='/';}
 if(!m)return <main className="accountPage"><p>프로필을 불러오는 중...</p></main>;
 return <main className="accountPage">
  <div className="accountHead"><div><a href="/">← 화성인사이드</a><h1>내 프로필</h1><p>@{user.username||'아이디 미등록'} · {user.email} · {user.role}</p></div><div>{['admin','editor'].includes(user.role)&&<a className="accountAdminBtn" href="/admin">관리자 페이지</a>}<button onClick={logout}>로그아웃</button></div></div>
  <div className="accountGrid"><section className="accountPhoto"><div>{m.profile_image_url?<img src={m.profile_image_url} alt="프로필"/>:<span>프로필 이미지</span>}</div><label>{uploading?'업로드 중...':'프로필 이미지 변경'}<input hidden type="file" accept="image/*" onChange={e=>uploadAsset(e,'profile_image_url','profiles',setUploading)}/></label><small>권장 1200×1200px · JPG/WEBP</small><a className="accountPreviewLink" href={m.id?`/members/${m.id}`:'/members'} target="_blank">내 상세페이지 미리보기 ↗</a></section>
  <section className="accountForm">
   <label>이름<input value={m.name||''} onChange={e=>set('name',e.target.value)}/></label><label>직업/직책<input value={m.job||''} onChange={e=>set('job',e.target.value)}/></label>
   <label className="wide">한 줄 소개 / 슬로건<input value={m.tagline||''} onChange={e=>set('tagline',e.target.value)} placeholder="예: 모두가 골고루 잘사는 성숙한 문화시민의 사회를 만듭니다."/></label>
   <label>나이<input type="number" value={m.age||''} onChange={e=>set('age',Number(e.target.value))}/></label><label>성별<input value={m.gender||''} onChange={e=>set('gender',e.target.value)}/></label><label>공개 이메일<input value={m.public_email||''} onChange={e=>set('public_email',e.target.value)}/></label><label>전화번호<input type="tel" value={m.phone||''} onChange={e=>set('phone',e.target.value)} placeholder="010-0000-0000"/></label><label>최종학력<input value={m.school||''} onChange={e=>set('school',e.target.value)}/></label><label>활동지역<input value={m.area||''} onChange={e=>set('area',e.target.value)}/></label>
   <label className="wide">전문분야 / 해시태그<input value={tagText} onChange={e=>setTagText(e.target.value)} onBlur={()=>{const tags=parseTags(tagText);set('tags',tags);setTagText(tags.join(', '))}} placeholder="마케팅,기획,디자인"/><small className="profileFieldHint">{tagGuide}</small></label>
   <label className="wide">개인정보 소개<textarea rows="8" value={m.intro||''} onChange={e=>set('intro',e.target.value)} placeholder="상세페이지의 ‘개인정보 소개’ 영역에 노출됩니다."/></label>
   <label className="wide">프로필 유튜브 URL<input value={m.youtube_url||''} onChange={e=>set('youtube_url',e.target.value)} placeholder="https://youtu.be/..."/></label>
   <div className="wide accountVideoThumbUpload"><div className="accountVideoThumbPreview">{m.youtube_thumbnail_url?<img src={m.youtube_thumbnail_url} alt="영상 썸네일 미리보기"/>:<span>16:9 영상 썸네일</span>}</div><div><b>상세페이지 유튜브 썸네일</b><p>URL을 입력하지 않고 이미지 파일을 직접 등록합니다. 권장 1600×900px.</p><label className="accountUploadBtn">{thumbUploading?'업로드 중...':'썸네일 이미지 선택'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>uploadAsset(e,'youtube_thumbnail_url','video-thumbnails',setThumbUploading)}/></label>{m.youtube_thumbnail_url&&<button type="button" className="accountRemoveThumb" onClick={()=>set('youtube_thumbnail_url','')}>썸네일 삭제</button>}</div></div>
   <div className="wide accountStrengths"><h3>나의 강점 셀프 어필</h3><p>창의 · 연결 · 통찰 · 공감 · 실행 · 성장 항목을 각각 0~100점으로 직접 평가해 주세요. 저장하면 내 상세페이지의 6각 레이더에 즉시 반영됩니다.</p><div>{strengthLabels.map(k=><label key={k}><span>{k}</span><input type="number" min="0" max="100" value={m.strengths?.[k]??80} onChange={e=>set('strengths',{...(m.strengths||defaultStrengths),[k]:Math.max(0,Math.min(100,Number(e.target.value)||0))})}/></label>)}</div></div>
   <div className="wide accountCareers"><div className="careerEditorHead"><div><h3>경력 · 이력</h3><p>경력은 추가·삭제할 수 있고, 위/아래 버튼으로 원하는 노출 순서를 직접 정할 수 있습니다.</p></div><button type="button" className="careerAddBtn" onClick={addCareer}>+ 경력 추가</button></div>{(m.careers||[]).map((c,i)=><div className="accountCareerRow" key={c._key||c.id||i}><div className="careerOrderBadge">{i+1}</div><div className="careerFields"><input placeholder="기간" value={c.period||''} onChange={e=>updateCareer(i,{period:e.target.value})}/><input placeholder="회사/기관" value={c.company||''} onChange={e=>updateCareer(i,{company:e.target.value})}/><input placeholder="역할" value={c.role||''} onChange={e=>updateCareer(i,{role:e.target.value})}/><input placeholder="설명" value={c.description||c.desc||''} onChange={e=>updateCareer(i,{description:e.target.value})}/></div><div className="careerRowActions"><button type="button" onClick={()=>moveCareer(i,-1)} disabled={i===0} aria-label="경력 위로 이동">↑ 위로</button><button type="button" onClick={()=>moveCareer(i,1)} disabled={i===(m.careers||[]).length-1} aria-label="경력 아래로 이동">↓ 아래로</button><button type="button" className="danger" onClick={()=>removeCareer(i)}>삭제</button></div></div>)}</div>
   <div className="wide accountSave"><button onClick={save}>프로필 저장</button><span>{msg}</span></div>
  </section></div>
 </main>
}
