'use client';
import { useEffect,useState } from 'react';
import { createClient } from '../../lib/supabase/client';
export default function AccountClient({user}){
 const [m,setM]=useState(null);const [msg,setMsg]=useState('');const [uploading,setUploading]=useState(false);
 useEffect(()=>{fetch('/api/profile').then(r=>r.json()).then(d=>{const member=d.member||{};member.careers=(member.careers||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));setM(member)});},[]);
 const set=(k,v)=>setM(p=>({...p,[k]:v}));
 async function save(){setMsg('저장 중...');const r=await fetch('/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(m)});const d=await r.json();setMsg(r.ok?'저장되었습니다.':d.error||'저장 실패');}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;setUploading(true);const fd=new FormData();fd.append('file',file);fd.append('folder','profiles');const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(r.ok)set('profile_image_url',d.url);else setMsg(d.error);setUploading(false)}
 async function logout(){const supabase=createClient();await supabase.auth.signOut();location.href='/';}
 if(!m)return <main className="accountPage"><p>프로필을 불러오는 중...</p></main>;
 return <main className="accountPage"><div className="accountHead"><div><a href="/">← 화성인사이드</a><h1>내 프로필</h1><p>{user.email} · {user.role}</p></div><div>{['admin','editor'].includes(user.role)&&<a className="accountAdminBtn" href="/admin">관리자 페이지</a>}<button onClick={logout}>로그아웃</button></div></div><div className="accountGrid"><section className="accountPhoto"><div>{m.profile_image_url?<img src={m.profile_image_url} alt="프로필"/>:<span>프로필 이미지</span>}</div><label>{uploading?'업로드 중...':'프로필 이미지 변경'}<input hidden type="file" accept="image/*" onChange={upload}/></label><small>권장 1200×1200px · JPG/WEBP</small></section><section className="accountForm"><label>이름<input value={m.name||''} onChange={e=>set('name',e.target.value)}/></label><label>직업/직책<input value={m.job||''} onChange={e=>set('job',e.target.value)}/></label><label>나이<input type="number" value={m.age||''} onChange={e=>set('age',Number(e.target.value))}/></label><label>성별<input value={m.gender||''} onChange={e=>set('gender',e.target.value)}/></label><label>공개 이메일<input value={m.public_email||''} onChange={e=>set('public_email',e.target.value)}/></label><label>최종학력<input value={m.school||''} onChange={e=>set('school',e.target.value)}/></label><label>활동지역<input value={m.area||''} onChange={e=>set('area',e.target.value)}/></label><label className="wide">해시태그<input value={(m.tags||[]).join(', ')} onChange={e=>set('tags',e.target.value.split(',').map(v=>v.trim()).filter(Boolean))}/></label><label className="wide">소개<textarea rows="7" value={m.intro||''} onChange={e=>set('intro',e.target.value)}/></label><div className="wide accountCareers"><h3>경력 · 이력</h3>{(m.careers||[]).map((c,i)=><div key={c.id||i}><input placeholder="기간" value={c.period||''} onChange={e=>{const a=[...(m.careers||[])];a[i]={...a[i],period:e.target.value};set('careers',a)}}/><input placeholder="회사/기관" value={c.company||''} onChange={e=>{const a=[...(m.careers||[])];a[i]={...a[i],company:e.target.value};set('careers',a)}}/><input placeholder="역할" value={c.role||''} onChange={e=>{const a=[...(m.careers||[])];a[i]={...a[i],role:e.target.value};set('careers',a)}}/><input placeholder="설명" value={c.description||c.desc||''} onChange={e=>{const a=[...(m.careers||[])];a[i]={...a[i],description:e.target.value};set('careers',a)}}/><button onClick={()=>set('careers',(m.careers||[]).filter((_,j)=>j!==i))}>삭제</button></div>)}<button onClick={()=>set('careers',[...(m.careers||[]),{period:'',company:'',role:'',description:''}])}>+ 경력 추가</button></div><div className="wide accountSave"><button onClick={save}>프로필 저장</button><span>{msg}</span></div></section></div></main>
}
