import { NextResponse } from 'next/server';
import { assertApiRole } from '../../../../lib/auth';
import { createAdminClient } from '../../../../lib/supabase/admin';

async function loadState(admin){
 const [{data:site},{data:members},{data:news}]=await Promise.all([admin.from('site_state').select('payload').eq('id','main').maybeSingle(),admin.from('members').select('*, careers(*)').order('id'),admin.from('news_posts').select('*').order('published_at',{ascending:false})]);
 const payload=site?.payload||{};return {data:{...payload,news:(news||[]).map(n=>({id:String(n.id),category:n.category,title:n.title,excerpt:n.excerpt,date:(n.published_at||n.created_at||'').slice(0,10).replaceAll('-','.'),coverUrl:n.cover_url||'',published:n.is_published,body:n.body||''}))},members:(members||[]).map(m=>({id:String(m.id),name:m.name,job:m.job,age:m.age,gender:m.gender,email:m.public_email||'',school:m.school||'',area:m.area||'',tier:m.tier||'Gold',featured:m.featured_rank!=null,tags:m.tags||[],intro:m.intro||'',image:m.profile_image_url||'',profileImage:m.profile_image_url||'',published:m.is_published,youtubeUrl:m.youtube_url||'',youtubeThumbnailUrl:m.youtube_thumbnail_url||'',careers:(m.careers||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(c=>({period:c.period||'',company:c.company||'',role:c.role||'',desc:c.description||''}))}))};
}
export async function GET(){const auth=await assertApiRole(['admin','editor']);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});return NextResponse.json(await loadState(createAdminClient()));}
export async function PUT(request){
 const auth=await assertApiRole(['admin','editor']);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const body=await request.json();const admin=createAdminClient();
 if(body.dataPatch&&Object.keys(body.dataPatch).length){const {data:existing}=await admin.from('site_state').select('payload').eq('id','main').maybeSingle();const payload={...(existing?.payload||{}),...body.dataPatch};await admin.from('site_state').upsert({id:'main',payload,updated_by:auth.user.id,updated_at:new Date().toISOString()});}
 if(Array.isArray(body.featuredIds)){await admin.from('members').update({featured_rank:null}).not('featured_rank','is',null);for(let i=0;i<body.featuredIds.length;i++)await admin.from('members').update({featured_rank:i+1}).eq('id',Number(body.featuredIds[i]));const {data:existing}=await admin.from('site_state').select('payload').eq('id','main').maybeSingle();await admin.from('site_state').upsert({id:'main',payload:{...(existing?.payload||{}),featuredIds:body.featuredIds},updated_by:auth.user.id,updated_at:new Date().toISOString()});}
 for(const m of body.changedMembers||[]){const row={id:Number(m.id),name:m.name||'',job:m.job||'',age:m.age||null,gender:m.gender||'',public_email:m.email||'',school:m.school||'',area:m.area||'',tier:m.tier||'Gold',tags:m.tags||[],intro:m.intro||'',profile_image_url:m.profileImage||m.image||'',is_published:m.published!==false,youtube_url:m.youtubeUrl||'',youtube_thumbnail_url:m.youtubeThumbnailUrl||'',updated_at:new Date().toISOString()};await admin.from('members').upsert(row,{onConflict:'id'});if(Array.isArray(m.careers)){await admin.from('careers').delete().eq('member_id',Number(m.id));if(m.careers.length)await admin.from('careers').insert(m.careers.map((c,i)=>({member_id:Number(m.id),sort_order:i,period:c.period||'',company:c.company||'',role:c.role||'',description:c.desc||''})));}}
 for(const n of body.changedNews||[]){await admin.from('news_posts').upsert({id:Number(n.id),category:n.category||'공지',title:n.title||'',excerpt:n.excerpt||'',body:n.body||'',cover_url:n.coverUrl||'',is_published:!!n.published,published_at:n.date?new Date(n.date.replaceAll('.','-')+'T00:00:00+09:00').toISOString():null,updated_at:new Date().toISOString()},{onConflict:'id'});}
 if((body.deletedNewsIds||[]).length)await admin.from('news_posts').delete().in('id',body.deletedNewsIds.map(Number));
 await admin.from('audit_logs').insert({actor_id:auth.user.id,action:'admin.patch_update',target_type:'site',target_id:'main',payload:{sections:Object.keys(body.dataPatch||{}),members:(body.changedMembers||[]).map(m=>m.id),news:(body.changedNews||[]).map(n=>n.id),featured:body.featuredIds||null}});
 return NextResponse.json({ok:true});
}
