'use client';
import { useRef,useState } from 'react';
export function PageTitle({title,desc,actions}){return <div className="adminPageTitle"><div><h1>{title}</h1><p>{desc}</p></div>{actions&&<div>{actions}</div>}</div>}
export function Card({title,desc,children,className=''}){return <section className={`adminCard ${className}`}><div className="adminCardHead"><div><h2>{title}</h2>{desc&&<p>{desc}</p>}</div></div>{children}</section>}
export function Field({label,hint,children}){return <label className="adminField"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Input(props){return <input className="adminInput" {...props}/>}
export function Textarea(props){return <textarea className="adminTextarea" {...props}/>}
export function Badge({children,type=''}){return <span className={`adminBadge ${type}`}>{children}</span>}
export function Spec({spec}){return <div className="adminSpec"><b>{spec.width} × {spec.height}px</b><span>{spec.ratio} · {spec.format}</span><small>{spec.note}</small></div>}
function imageSize(file){return new Promise((resolve,reject)=>{if(file.type==='image/svg+xml')return resolve(null);const img=new Image();const url=URL.createObjectURL(file);img.onload=()=>{resolve({width:img.naturalWidth,height:img.naturalHeight});URL.revokeObjectURL(url)};img.onerror=()=>{reject(new Error('이미지를 읽을 수 없습니다.'));URL.revokeObjectURL(url)};img.src=url})}
export function ImageUploader({label,value,onChange,spec}){
 const ref=useRef();const [state,setState]=useState('');
 async function handle(e){const file=e.target.files?.[0];if(!file)return;try{setState('검사 중...');const size=await imageSize(file);if(spec&&size){const expected=spec.width/spec.height;const actual=size.width/size.height;const ratioGap=Math.abs(actual-expected)/expected;if(size.width<spec.width||size.height<spec.height)throw new Error(`해상도가 작습니다. 최소 ${spec.width}×${spec.height}px 이상으로 등록하세요.`);if(ratioGap>.05)throw new Error(`이미지 비율이 다릅니다. ${spec.ratio} 비율로 준비해 주세요.`)}setState('업로드 중...');const fd=new FormData();fd.append('file',file);fd.append('folder',label.includes('프로필')?'profiles':label.includes('뉴스')?'news':label.includes('의장')?'chair':'site');const r=await fetch('/api/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'업로드 실패');onChange(d.url);setState('업로드 완료');}catch(err){setState(err.message||'업로드 실패');}finally{if(ref.current)ref.current.value=''}}
 return <div className="adminUpload"><div className="adminUploadPreview">{value?<img src={value} alt="업로드 미리보기"/>:<span>이미지 미리보기</span>}</div><div className="adminUploadBody"><b>{label}</b>{spec&&<Spec spec={spec}/>}<div className="adminUploadBtns"><button type="button" className="adminBtn primary" onClick={()=>ref.current?.click()}>이미지 선택</button>{value&&<button type="button" className="adminBtn" onClick={()=>onChange('')}>삭제</button>}</div>{state&&<small className="adminUploadStatus">{state}</small>}<input ref={ref} type="file" accept="image/jpeg,image/png,image/webp,image/svg+xml" hidden onChange={handle}/></div></div>
}
