-- 화성인사이드 v6.4 운영/상세프로필 확장 마이그레이션
-- 기존 v6 SQL을 실행한 프로젝트에서도 다시 실행해도 안전합니다.
alter table public.members add column if not exists youtube_url text default '';
alter table public.members add column if not exists youtube_thumbnail_url text default '';
alter table public.members add column if not exists tagline text default '';
alter table public.members add column if not exists strengths jsonb not null default '{"분석":80,"공감":80,"연결":80,"성장":80,"창의":80,"실행":80}'::jsonb;

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  board_type text not null check (board_type in ('notice','community')),
  title text not null default '', body text not null default '', excerpt text default '', cover_url text default '', youtube_url text default '',
  author_id uuid references auth.users(id) on delete set null, author_name text default '', is_published boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.board_posts enable row level security;
drop policy if exists "board_public_read" on public.board_posts;
create policy "board_public_read" on public.board_posts for select using (is_published = true or author_id = auth.uid() or public.my_role() in ('admin','editor'));
