-- 화성인사이드 v6 운영형 업그레이드
-- v5.2 적용 후 Supabase SQL Editor에서 1회 실행

alter table public.members add column if not exists youtube_url text default '';
alter table public.members add column if not exists youtube_thumbnail_url text default '';

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  board_type text not null check (board_type in ('notice','community')),
  title text not null default '',
  body text not null default '',
  excerpt text default '',
  cover_url text default '',
  youtube_url text default '',
  author_id uuid references auth.users(id) on delete set null,
  author_name text default '',
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists board_posts_type_created_idx on public.board_posts(board_type, created_at desc);

alter table public.board_posts enable row level security;

drop policy if exists "board_public_read" on public.board_posts;
create policy "board_public_read" on public.board_posts for select using (is_published = true or author_id = auth.uid() or public.my_role() in ('admin','editor'));

-- 쓰기/수정/삭제는 앱 서버에서 인증 후 service role로 처리합니다.

insert into public.board_posts(board_type,title,body,excerpt,cover_url,author_name,is_published,created_at,updated_at)
select 'notice',n.title,coalesce(nullif(n.body,''),n.excerpt),n.excerpt,n.cover_url,'화성인사이드',n.is_published,coalesce(n.published_at,n.created_at),n.updated_at
from public.news_posts n
where not exists (select 1 from public.board_posts b where b.board_type='notice' and b.title=n.title);
